(function() {
window.wordList = [
    ['äpple','apple'],
    ['hus','house'],
    ['katt','cat'],
    ['bok','book'],
    ['hund','dog'],
    ['bord','table'],
    ['stol','chair'],
    ['bil','car'],
    ['träd','tree'],
    ['fönster','window'],
    ['mat','food'],
    ['vatten','water'],
    ['sked','spoon'],
    ['gaffel','fork'],
    ['kniv','knife'],
    ['skola','school'],
    ['dator','computer'],
    ['telefon','phone'],
    ['säng','bed'],
    ['soffa','sofa'],
    ['ljus','light'],
    ['vägg','wall'],
    ['golv','floor'],
    ['tak','ceiling'],
    ['penna','pen'],
    ['papper','paper'],
    ['djur','animal'],
    ['fisk','fish'],
    ['fågel','bird'],
    ['sko','shoe'],
    ['toffla','slipper'],
    ['jacka','jacket'],
    ['rock','coat'],
    ['barn','child'],
    ['författare','author'],
    ['lärare','teacher'],
    ['student','student'],
    ['måne','moon'],
    ['sol','sun'],
    ['skugga','shadow'],
    ['stad','city'],
    ['bro','bridge'],
    ['väg','road'],
    ['bilväg','highway'],
    ['flygplan','airplane'],
    ['båt','boat'],
    ['cykel','bicycle'],
    ['hustak','rooftop'],
    ['skog','forest'],
    ['fält','field'],
    ['berg','mountain'],
    ['sjö','lake'],
    ['hav','sea'],
    ['sand','sand'],
    ['strand','beach'],
    ['äppelträd','apple tree'],
    ['blommor','flowers'],
    ['ros','rose'],
    ['tulpan','tulip'],
    ['skorsten','chimney'],
    ['eld','fire'],
    ['rök','smoke'],
    ['gräs','grass'],
    ['blad','leaf'],
    ['rutnät','grid'],
    ['knapp','button'],
    ['ana','hint'],
    ['graf','graph'],
    ['gräns','border'],
    ['väska','bag'],
    ['klocka','clock'],
    ['väggklocka','wall clock'],
    ['paraply','umbrella'],
    ['stadshus','city hall'],
    ['katedral','cathedral'],
    ['lampa','lamp'],
    ['himmel','sky'],
    ['stjärna','star'],
    ['universum','universe'],
    ['tidskrift','magazine'],
    ['tidning','newspaper'],
    ['bokhylla','bookshelf'],
    ['galleri','gallery'],
    ['butik','store'],
    ['marknad','market'],
    ['kundvagn','shopping cart'],
    ['grönsak','vegetable'],
    ['frukt','fruit'],
    ['apelsin','orange'],
    ['pärm','binder'],
    ['kudde','pillow'],
    ['filt','blanket'],
    ['ko','cow'],
    ['häst','horse'],
    ['gris','pig'],
    ['varg','wolf'],
    ['räv','fox'],
    ['igelkott','hedgehog'],
    ['spruta','syringe'],
    ['läkare','doctor'],
    ['sjukhus','hospital'],
    ['apotek','pharmacy'],
    ['ambulans','ambulance'],
    ['polis','police'],
    ['eldbil','fire truck'],
    ['tåg','train'],
    ['lok','locomotive'],
    ['station','station'],
    ['perrong','platform'],
    ['buss','bus'],
    ['taxi','taxi'],
    ['motorcykel','motorcycle'],
    ['elcykel','electric bicycle'],
    ['vägskena','rail'],
    ['karta','map'],
    ['hemsida','website'],
    ['skärm','screen'],
    ['böcker','books'],
    ['bibliotek','library'],
    ['prov','exam'],
    ['ordbok','dictionary'],
    ['lärohäft','workbook'],
    ['ämne','subject'],
    ['tal','number'],
    ['skor','shoes'],
    ['fabrik','factory'],
    ['verktyg','tool'],
    ['byrå','desk'],
    ['bordslampa','table lamp'],
    ['handduk','towel'],
    ['torktumlare','dryer'],
    ['diskmaskin','dishwasher'],
    ['spis','stove'],
    ['ugn','oven'],
    ['panna','pan'],
    ['stekpanna','frying pan'],
    ['mjölk','milk'],
    ['mjöl','flour'],
    ['socker','sugar'],
    ['te','tea'],
    ['kaffe','coffee'],
    ['diskho','sink'],
    ['tvättkorg','laundry basket'],
    ['tvätt','laundry'],
    ['toalett','toilet'],
    ['handfat','washbasin'],
    ['sängbord','bedside table'],
    ['äng','meadow'],
    ['trädgård','garden'],
    ['dam','pond'],
    ['lejon','lion'],
    ['orm','snake'],
    ['giraff','giraffe'],
    ['groda','frog'],
    ['elefant','elephant'],
    ['flugor','flies'],
    ['bi','bee'],
    ['spindel','spider'],
    ['farfar','grandfather'],
    ['mormor','grandmother'],
    ['morfar','grandfather (maternal)'],
    ['syskon','siblings'],
    ['kusin','cousin'],
    ['moster','aunt'],
    ['farbror','uncle'],
    ['kusinbarn','cousins child'],
    ['syrra','sister'],
    ['bror','brother'],
    ['vän','friend'],
    ['partner','partner'],
    ['älskare','lover'],
    ['brukare','user'],
    ['hyra','tenant'],
    ['kostym','suit'],
    ['klänning','dress'],
    ['kjol','skirt'],
    ['tröja','sweater'],
    ['blus','blouse'],
    ['långkalsong','thermal underwear'],
    ['handskar','gloves'],
    ['mössa','hat'],
    ['hatt','cap'],
    ['hårband','headband'],
    ['sandal','sandal'],
    ['solglasögon','sunglasses'],
    ['lärare','teacher'],
    ['rektorshus','principals house'],
    ['piano','piano'],
    ['fiol','violin'],
    ['gitarr','guitar'],
    ['banan','banana'],
    ['körsbär','cherry'],
    ['vattenmelon','watermelon'],
    ['granatäpple','pomegranate'],
    ['ost','cheese'],
    ['bröd','bread'],
    ['tomat','tomato'],
    ['gurka','cucumber'],
    ['glas','glass'],
    ['flaska','bottle'],
    ['burk','jar'],
    ['motor','engine'],
    ['hjärtat','heart'],
    ['tentamen','exam'],
    ['matgästen','diner guest'],
    ['bananfluga','fruit fly'],
    ['cykeldress','cycling jersey'],
    ['vätska','liquid'],
    ['undersökning','investigation'],
    ['tavla','painting'],
    ['matbord','dining table'],
    ['kaffekopp','coffee cup'],
    ['fika','snack'],
    ['frulle','breakfast'],
    ['matsal','dining room'],
    ['kaffebönor','coffee beans'],
    ['sovsäck','sleeping bag'],
    ['luftballong','hot air balloon'],
    ['vägskäl','crossroads'],
    ['knut','knot'],
    ['gardiner','curtains'],
    ['teater','theater'],
    ['scen','stage'],
    ['skiva','record'],
    ['bio','cinema'],
    ['kamera','camera'],
    ['film','film'],
    ['musik','music'],
    ['kompositör','composer'],
    ['målare','painter'],
    ['konst','art'],
    ['svär','oath'],
    ['gåva','gift'],
    ['papegojfågel','parrot'],
    ['flodhäst','hippopotamus'],
    ['ornament','ornament'],
    ['hemmet','the home'],
    ['fönsterkarm','window frame'],
    ['sekund','second'],
    ['minut','minute'],
    ['klockslag','time of day'],
    ['tråd','thread'],
    ['sytråd','sewing thread'],
    ['gäng','crowd'],
    ['folk','people'],
    ['vänskap','friendship'],
    ['läge','position'],
    ['land','country'],
    ['botten','bottom'],
    ['stol','chair'],
    ['konduktör','conductor'],
    ['fiskkorg','fish basket'],
    ['karaktär','character'],
    ['utseende','appearance'],
    ['träning','training'],
    ['enighet','unity'],
    ['företgång','precedent'],
    ['kultur','culture'],
    ['ekonomi','economy'],
    ['politik','politics'],
    ['bönder','peasants'],
    ['majoritet','majority'],
    ['minoritet','minority'],
    ['kung','king'],
    ['drottning','queen'],
    ['prins','prince'],
    ['prinsessa','princess'],
    ['onkel','uncle'],
    ['tant','aunt'],
    ['son','son'],
    ['dotter','daughter'],
    ['babysits','baby seat'],
    ['vagn','wagon'],
    ['barnstol','high chair'],
    ['klätterställning','climbing frame'],
    ['svans','tail'],
    ['ratt','steering wheel'],
    ['puls','pulse'],
    ['väg','road'],
    ['fjäril','butterfly'],
    ['lämmel','lemming'],
    ['storm','storm'],
    ['vattennivå','water level'],
    ['kedja','chain'],
    ['stång','pole'],
    ['grått','gray'],
    ['svart','black'],
    ['rosa','pink'],
    ['silver','silver'],
    ['röst','voice'],
    ['ek','oak'],
    ['kapell','chapel'],
    ['sal','hall'],
    ['fack','compartment'],
    ['slott','castle'],
    ['arbete','work'],
    ['dröm','dream'],
    ['värld','world'],
    ['tid','time'],
    ['liv','life'],
    ['framtid','future'],
    ['idag','today'],
    ['igår','yesterday'],
    ['imorgon','tomorrow'],
    ['vara','being'],
    ['egen','own'],
    ['förlust','loss'],
    ['kapten','captain'],
    ['sjöman','sailor'],
    ['skatt','treasure'],
    ['produktion','production'],
    ['jord','earth'],
    ['konkurs','bankruptcy'],
    ['hypotek','mortgage'],
    ['stadium','stadium'],
    ['högstadium','junior high school'],
    ['räddning','rescue'],
    ['dammsugare','vacuum cleaner'],
    ['mopp','mop'],
    ['såpa','soap'],
    ['skylt','sign'],
    ['utrymme','space'],
    ['växt','plant'],
    ['kvarter','block'],
    ['rymd','space'],
    ['skott','shot'],
    ['raket','rocket'],
    ['radio','radio'],
    ['tv','TV'],
    ['höstdag','autumn day'],
    ['kylskåp','refrigerator'],
    ['frys','freezer'],
    ['kryddhylla','spice rack'],
    ['grytlappar','oven mitt'],
    ['pipett','pipette'],
    ['gräsmördare','grass murderer'],
    ['hörselnäck','ear cochlea'],
    ['blixt','lightning'],
    ['pådrag','commotion'],
    ['vattenpump','water pump'],
    ['paraplyställ','umbrella stand'],
    ['muggställ','mug stand'],
    ['tvättmaskin','washing machine'],
    ['lyktgolvlampa','floor lamp'],
    ['sovsäck','sleeping bag'],
    ['klätterrep','climbing rope'],
    ['gungstol','rocking chair'],
    ['sjöutsikt','lake view'],
    ['fotboll','football'],
    ['basketboll','basketball'],
    ['tennisboll','tennis ball'],
    ['läderjacka','leather jacket'],
    ['växthus','greenhouse'],
    ['gräsmatta','lawn'],
    ['cykelställ','bicycle rack'],
    ['källaren','cellar'],
    ['vinden','attic'],
    ['våning','floor'],
    ['taklampor','ceiling lamps']
];
})();
